#include "help.h"

char const * const main_help_fmt =
	"%s - Manage files on TI-nspire devices\n"                                                                                                             >)
	"\n"
	"Usage:\n"
	"  %s [option]... <command> [<args>]\n"
	"\n"
	"Description:\n"
	"  A simple wrapper for the libnspire functions as a command line tool. I made\n"
	"  this mostly because I just cant get tilp to work, but the raw functions do.\n"
	"  If there's any mistakes or you have any suggestions, even tiny little picky\n"
	"  ones, please dont hesitate to contact me or submit a pull request.\n"
	"\n"
	"Commands:\n"
	"  send        Send files to the device\n"
	"  read        Read a file from the device\n"
	"  list        List files on the device\n"
	"  move        Move or rename files\n"
	"  copy        Duplicate files\n"
	"  info        Show OS and device information\n"
	"  help        Show this help or help for a command\n"
	"\n"
	"Options:\n"
	"  -v, --verbose     log what is being done\n"
	"  -d, --debug       print out values as well (implies -v)\n"
	"      --help        show this help\n"
	"\n"
	"Run '%s help <command>' for details.\n"
;

char const * const send_help_fmt =
	"%s send - send files to the connected calculator"
	"\n"
	"Usage:\n"
	"  %s send <file>... <destination>\n"
	"\n"
	"Description:\n"
	"  Copies one or more files to the specified directory on the connected TI-nspire\n"
	"  device.\n"
	"  \n"
	"  The path is relative to the \"My Documents\" folder in calculator. That is the\n"
	"  folder that every file is in when you press \"Browse\" in the home screen.\n"
	"  Paths beginning with a slash to denote root (for example `/folder/file.tns`)\n"
	"  are also placed relative to the \"My Documents\" folder. This means\n"
	"  `/folder/file.tns` and `folder/file.tns` refer to the same file.\n"
   "\n"
   "Options:\n"
   // "  -f, --force        Overwrite existing file\n"
   "      --help         show this help\n"
;

char const * const read_help_fmt =
	"%s read - reads a file and prints its contents to stdout\n"
	"\n"
	"Usage:\n"
	"  %s read [option]... <file>...\n"
	"\n"
	"Options:\n"
	"  -o <file>         send output to a file instead of stdout. the file must exist\n"
	"                    and it overwrites its contents.\n"
	"      --help        show this help\n"
;

char const * const list_help_fmt =
	"%s list - list the files and folders in a specified directory\n"
	"\n"
	"Usage:\n"
	"  %s list [option]... <file>...\n"
	"\n"
	"Description:\n"
	"  Reads a file and prints its contents to stdout\n"
	"\n"
	"Options:\n"
	"      --no-format   dont format the list\n"
	"      --help        show this help\n"
;

char const * const moveCopy_help_fmt =
	"%s move, %s copy - move or copy a file within the calculator\n"
	"\n"
	"Usage:\n"
	"  %s move [option]... <file>... <directory>\n"
	"  %s move [option]... <file> <destination>\n"
	"  \n"
	"  %s copy [option]... <file>... <directory>\n"
	"  %s copy [option]... <file> <destination>\n"
	"\n"
	"Description:\n"
	"  Renames/duplicates <file> to <destination>, or moves/duplicates <file>(s) to\n"
	"  <directory>.\n"
	"  \n"
	"  A directory is denoted by a '/' at the end, multiple files being specified\n"
	"  or already existing in the file system as a folder. A slash ('/') is added\n"
	"  between <file> and <directory> if one is required to make a valid path.\n"
	"\n"
	"Options:\n"
	"      --help        show this help\n"
;

char const * const info_help_fmt =
	"%s info - get information related to the connected calculator\n"
	"\n"
	"Usage:\n"
	"  %s info\n"
	"\n"
	"Description:\n"
	"  Prints out all the fields filled in by `nspire_device_info` and formats it.\n"
	"  The libnspire library is missing 0x1c from the type code enum, so I assumed\n"
	"  it's whether or not the calculator is a CAS. If thats wrong, there's any\n"
	"  other mistakes, or you have an improvement please contant me or submit a pull\n"
	"  request.\n"
	"\n"
	"Options:\n"
	"      --help        show this help\n"
;
